// Víbora Padel service worker: makes the installed app (and the site) work offline.
//
// - Install: precaches the app shell, every module, the MediaPipe runtime and the default
//   'full' pose model, hands, fonts and icons (PRECACHE, generated by tools/precache.mjs with a
//   content hash per file). Files whose hash did not change are copied from the previous
//   version's cache instead of downloaded again, so an update only fetches what changed.
// - Fetch, same-origin requests inside the scope only (everything else, e.g. the googleapis
//   telemetry that src/app/privacy.js blocks, is never touched or cached):
//     * pages, src/, styles/, the manifest: network first (revalidated, 4 s timeout), cache
//       fallback, so updates arrive as soon as they are deployed and the app still opens offline;
//     * vendor/, models/, assets/, fonts/, icons/: cache first (immutable), filled at runtime for
//       files outside the precache (the lite / heavy models, the non-SIMD wasm build).
// - Activate: deletes caches of older versions and claims open pages.
// - Messages: 'SKIP_WAITING' (the page's "Update ready — restart"), 'CACHE_URLS' (the page lists
//   what it loaded on the first visit, before this worker controlled it), 'STATUS'.
// All paths are relative to this file, so it works from a GitHub Pages sub-path.

const VERSION = '2857ea4587';
const PREFIX = 'vibora-';
const PRECACHE_NAME = `${PREFIX}precache-${VERSION}`;
const RUNTIME_NAME = `${PREFIX}runtime-v1`;
const META_KEY = '__vibora-precache-meta';
const NETWORK_TIMEOUT_MS = 4000;
const IMMUTABLE = /^(vendor|models|assets|fonts|icons)\//;
const BASE = new URL('./', self.location).href;

const PRECACHE = [
  /* PRECACHE:START */
  ['assets/hands/left.glb', 'bc6778314494'],
  ['assets/hands/right.glb', '291790c14f7f'],
  ['fonts/barlow-semi-condensed-latin-400-normal.woff2', 'd03a7a5f6b74'],
  ['fonts/barlow-semi-condensed-latin-600-normal.woff2', 'f158417e9207'],
  ['fonts/barlow-semi-condensed-latin-700-normal.woff2', 'fb958c8c20a0'],
  ['fonts/big-shoulders-display-latin-800-normal.woff2', '088f423f0913'],
  ['fonts/big-shoulders-display-latin-900-normal.woff2', '65f2c3680342'],
  ['icons/apple-touch-icon.png', '4bf2ebf08796'],
  ['icons/favicon-32.png', 'd2d1a0a518ee'],
  ['icons/favicon.svg', '485c62044a66'],
  ['icons/icon-192.png', '584af330ba6a'],
  ['icons/icon-512.png', '19e6b380d873'],
  ['icons/icon-maskable-192.png', '05bfa3fcd6c7'],
  ['icons/icon-maskable-512.png', 'd61329445212'],
  ['icons/icon-maskable.svg', '869fec64bdbc'],
  ['icons/icon.svg', 'ec4ab0a9d441'],
  ['index.html', 'c05380d0dcb1'],
  ['manifest.webmanifest', '173fd9b9c559'],
  ['models/pose_landmarker_full.task', '4eaa5eb7a983'],
  ['src/app/aids.js', 'e419d3c8cd7e'],
  ['src/app/autofeed.js', '1961a100241c'],
  ['src/app/clock.js', '7c23fa4b5ade'],
  ['src/app/debug.js', 'a99fd711c9bb'],
  ['src/app/diagnostics.js', 'b888680371e1'],
  ['src/app/game.js', '4f5dae590102'],
  ['src/app/params.js', 'f04248643424'],
  ['src/app/privacy.js', '50eb439e7303'],
  ['src/app/pwa.js', 'bca54ca44c0a'],
  ['src/app/replay.js', 'd3754670ca4a'],
  ['src/app/settings.js', '2fa4a96edb72'],
  ['src/app/stage.js', 'e7d528ee4cb7'],
  ['src/app/tracking.js', 'afb190d2f64b'],
  ['src/app/wiring.js', 'a71508780c8f'],
  ['src/audio/engine.js', 'f66bc0cf6d16'],
  ['src/audio/voice.js', 'c1f358c7a4d7'],
  ['src/config.js', '04b54eb4474c'],
  ['src/game/coach.js', '69798379789a'],
  ['src/game/drills.js', '4354572d0a98'],
  ['src/game/human.js', '6b3c0bd875f6'],
  ['src/game/intercept.js', '17cb4f6ae2c7'],
  ['src/game/machine.js', 'ead0622a83e2'],
  ['src/game/modes.js', '27c7cb7cfce5'],
  ['src/game/session.js', 'b9007c222deb'],
  ['src/game/swingAssist.js', '1c12c7d6c972'],
  ['src/game/swingPredict.js', '023ed6f83b94'],
  ['src/game/tactics.js', '311af45ec1b2'],
  ['src/game/world.js', 'e524a4faa1a4'],
  ['src/input/fallback.js', '692601ba45a8'],
  ['src/main.js', 'ea7d499b66eb'],
  ['src/physics/ball.js', 'a8bd0cc6cc8b'],
  ['src/physics/court.js', 'd68e2a69340e'],
  ['src/physics/history.js', 'bb43a6a8d33c'],
  ['src/physics/predict.js', '1f0abc4ce7d8'],
  ['src/physics/racket.js', 'cd2fc76e15f1'],
  ['src/render/actorKit.js', 'a53a6793af3e'],
  ['src/render/armFade.js', 'b897096a29bc'],
  ['src/render/ballView.js', '122c81a52b76'],
  ['src/render/effects.js', '4ea7e19b2632'],
  ['src/render/environment.js', '7786ff0ac7e6'],
  ['src/render/fpCamera.js', 'fcffd9a60b67'],
  ['src/render/fpRig.js', '64699f44f35c'],
  ['src/render/gaze.js', '5ac55c45a1e0'],
  ['src/render/handPose.js', 'a961c4a70816'],
  ['src/render/humanoid.js', '29828e65a217'],
  ['src/render/machineView.js', '94186e939b33'],
  ['src/render/racket.js', 'd7dd9a24d0ce'],
  ['src/render/rearView.js', '0470b663c05e'],
  ['src/render/reconcile.js', '1e2f90d6235e'],
  ['src/render/safeView.js', 'faf2ed1b238b'],
  ['src/render/scene.js', '5b43a548fbcf'],
  ['src/render/textures.js', 'ce772692df86'],
  ['src/render/viewClamp.js', '5c3250447ec8'],
  ['src/rules/referee.js', '3a68b89c9bb5'],
  ['src/rules/scoring.js', '6bf48b1a17a1'],
  ['src/tracking/autopilot.js', '65f4acab6b8d'],
  ['src/tracking/body.js', '3cd909c8953d'],
  ['src/tracking/camera.js', '03d20f3c48ec'],
  ['src/tracking/locomotion.js', '0c5a5fb7d336'],
  ['src/tracking/pose.js', '8f396bc48042'],
  ['src/tracking/racketTrack.js', 'c8c30fb34c2f'],
  ['src/tracking/swing.js', '3eec5c9ba565'],
  ['src/tracking/synthetic.js', 'eaa23d36b6b8'],
  ['src/ui/charts.js', '8254f3655837'],
  ['src/ui/cursor.js', '41dffd92754d'],
  ['src/ui/ui.js', '6b3eb83d2fa4'],
  ['src/util/math.js', 'b66debccdb3a'],
  ['src/util/vec3.js', 'f5fead0fc287'],
  ['src/xr/axis.js', 'af67d84f4b4e'],
  ['src/xr/boot.js', '9ca2749e73b2'],
  ['src/xr/display.js', '759e98236b72'],
  ['src/xr/glasses.js', 'db2a1f01b90a'],
  ['src/xr/hudText.js', '56e301b72e91'],
  ['src/xr/panel.js', '2533b91858a0'],
  ['src/xr/protocol.js', '7dd8afdb75d8'],
  ['src/xr/quat.js', '21665b8de60d'],
  ['src/xr/sim.js', '696801c2cd22'],
  ['src/xr/stereo.js', 'd5a29c41806f'],
  ['src/xr/styles.js', 'f1fc0323bb20'],
  ['src/xr/viture.js', '1b2ff4d3e373'],
  ['styles/app.css', '1ab9aaae100a'],
  ['vendor/mediapipe/vision_bundle.mjs', 'd885630c297c'],
  ['vendor/mediapipe/wasm/vision_wasm_internal.js', 'e170ee67dd4e'],
  ['vendor/mediapipe/wasm/vision_wasm_internal.wasm', '8da277a73392'],
  ['vendor/three/addons/environments/RoomEnvironment.js', '55f466192cc8'],
  ['vendor/three/addons/geometries/RoundedBoxGeometry.js', 'c5feab961238'],
  ['vendor/three/addons/loaders/GLTFLoader.js', '131c0f78c01d'],
  ['vendor/three/addons/postprocessing/EffectComposer.js', '4e079a588615'],
  ['vendor/three/addons/postprocessing/FXAAPass.js', 'aa4e87a28f57'],
  ['vendor/three/addons/postprocessing/MaskPass.js', '7cd08eee9d5d'],
  ['vendor/three/addons/postprocessing/OutputPass.js', '02e4a261af34'],
  ['vendor/three/addons/postprocessing/Pass.js', '444b409c235e'],
  ['vendor/three/addons/postprocessing/RenderPass.js', '817f6c3cdcd0'],
  ['vendor/three/addons/postprocessing/ShaderPass.js', 'e2500a5913b2'],
  ['vendor/three/addons/postprocessing/UnrealBloomPass.js', 'ba8f2fcadfa6'],
  ['vendor/three/addons/shaders/CopyShader.js', 'a33057d5ac91'],
  ['vendor/three/addons/shaders/FXAAShader.js', 'b8303d179f9d'],
  ['vendor/three/addons/shaders/LuminosityHighPassShader.js', '5044f780b6e6'],
  ['vendor/three/addons/shaders/OutputShader.js', '353479f77a8d'],
  ['vendor/three/addons/utils/BufferGeometryUtils.js', '9fb63427ce66'],
  ['vendor/three/addons/utils/SkeletonUtils.js', 'b1632a703206'],
  ['vendor/three/three.core.js', '9edde002b066'],
  ['vendor/three/three.module.js', '9052042d676c'],
  /* PRECACHE:END */
];

const abs = (p) => new URL(p, BASE).href;
const relOf = (url) => (url.startsWith(BASE) ? url.slice(BASE.length).split(/[?#]/)[0] : null);
const cacheable = (res) => res && res.ok && res.status === 200 && (res.type === 'basic' || res.type === 'default');

async function broadcast(msg) {
  const list = await self.clients.matchAll({ includeUncontrolled: true, type: 'window' });
  for (const c of list) c.postMessage(msg);
}

/** Previous precache (newest other version) and its { path: hash } map, for reuse. */
async function previousPrecache() {
  const names = (await caches.keys()).filter((n) => n.startsWith(`${PREFIX}precache-`) && n !== PRECACHE_NAME);
  for (const name of names.reverse()) {
    const cache = await caches.open(name);
    const meta = await cache.match(abs(META_KEY));
    if (!meta) continue;
    try {
      return { cache, hashes: await meta.json() };
    } catch {
      /* unreadable: try the next one */
    }
  }
  return null;
}

async function precache() {
  const cache = await caches.open(PRECACHE_NAME);
  const prev = await previousPrecache();
  const hashes = {};
  let done = 0;
  let lastReport = 0;
  const queue = PRECACHE.slice();
  const worker = async () => {
    for (;;) {
      const item = queue.shift();
      if (!item) return;
      const [path, hash] = item;
      const url = abs(path);
      let res = null;
      if (prev && prev.hashes[path] === hash && hash) res = await prev.cache.match(url);
      if (!res) {
        res = await fetch(new Request(url, { cache: 'no-cache', credentials: 'same-origin' }));
        if (res.status === 404) {
          // Listed but no longer on the server: the app cannot need it.
          done++;
          continue;
        }
        if (!cacheable(res)) throw new Error(`precache ${path}: HTTP ${res.status}`);
      }
      await cache.put(url, res);
      hashes[path] = hash;
      done++;
      if (done - lastReport >= 8 || done === PRECACHE.length) {
        lastReport = done;
        broadcast({ type: 'vibora-sw-progress', version: VERSION, done, total: PRECACHE.length });
      }
    }
  };
  await Promise.all(Array.from({ length: 6 }, worker));
  await cache.put(abs(META_KEY), new Response(JSON.stringify(hashes), { headers: { 'Content-Type': 'application/json' } }));
}

self.addEventListener('install', (event) => {
  event.waitUntil(precache());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keep = new Set([PRECACHE_NAME, RUNTIME_NAME]);
    for (const name of await caches.keys()) {
      if (name.startsWith(PREFIX) && !keep.has(name)) await caches.delete(name);
    }
    if (self.registration.navigationPreload) {
      try {
        await self.registration.navigationPreload.disable();
      } catch {
        /* not supported */
      }
    }
    await self.clients.claim();
    broadcast({ type: 'vibora-sw-ready', version: VERSION });
  })());
});

async function fromCache(url) {
  const pre = await caches.open(PRECACHE_NAME);
  const hit = await pre.match(url, { ignoreSearch: true });
  if (hit) return hit;
  const rt = await caches.open(RUNTIME_NAME);
  return rt.match(url, { ignoreSearch: true });
}

function timeout(ms) {
  return new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), ms));
}

/** Network first (revalidated), cache fallback; fresh copies replace the cached ones. */
async function networkFirst(request, key) {
  try {
    // A navigation request cannot be re-initialised; everything else is revalidated.
    const net = request.mode === 'navigate' ? fetch(request) : fetch(request, { cache: 'no-cache' });
    const res = await Promise.race([net, timeout(NETWORK_TIMEOUT_MS)]);
    if (cacheable(res)) {
      const copy = res.clone();
      caches.open(PRECACHE_NAME).then((c) => c.put(key, copy)).catch(() => {});
      return res;
    }
    if (res.status < 500) return res; // a real 404 etc.: pass it on
    throw new Error(`HTTP ${res.status}`);
  } catch (err) {
    const hit = await fromCache(key);
    if (hit) return hit;
    throw err;
  }
}

/** Cache first; misses are fetched and kept in the runtime cache. */
async function cacheFirst(request, key) {
  const hit = await fromCache(key);
  if (hit) return hit;
  const res = await fetch(request);
  if (cacheable(res)) {
    const copy = res.clone();
    caches.open(RUNTIME_NAME).then((c) => c.put(key, copy)).catch(() => {});
  }
  return res;
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || req.headers.has('range')) return;
  const rel = relOf(req.url);
  if (rel === null) return; // other origins (and paths outside the scope): not ours
  if (rel === 'sw.js' || rel.startsWith('tools/') || rel.startsWith('tests/')) return;
  // The app's page is cached once as index.html, whatever its query (?source=app, ?drill=…).
  const key = rel === '' || rel === 'index.html' ? abs('index.html') : abs(rel);
  if (req.mode === 'navigate') {
    event.respondWith(networkFirst(req, key));
    return;
  }
  event.respondWith(IMMUTABLE.test(rel) ? cacheFirst(req, key) : networkFirst(req, key));
});

async function cacheUrls(urls) {
  const rt = await caches.open(RUNTIME_NAME);
  for (const u of urls || []) {
    const rel = typeof u === 'string' ? relOf(u) : null;
    if (rel === null || rel === '' || rel === 'sw.js' || /^(tools|tests|dev)\//.test(rel)) continue;
    const key = abs(rel);
    if (await fromCache(key)) continue;
    try {
      const res = await fetch(key, { cache: 'no-cache' });
      if (cacheable(res)) await rt.put(key, res);
    } catch {
      /* offline: next time */
    }
  }
}

async function status() {
  const pre = await caches.open(PRECACHE_NAME);
  const keys = await pre.keys();
  const have = new Set(keys.map((r) => r.url));
  const missing = PRECACHE.filter(([p]) => !have.has(abs(p))).map(([p]) => p);
  return { version: VERSION, precached: PRECACHE.length - missing.length, total: PRECACHE.length, missing: missing.slice(0, 20) };
}

self.addEventListener('message', (event) => {
  const msg = event.data || {};
  const reply = (data) => {
    if (event.ports && event.ports[0]) event.ports[0].postMessage(data);
    else if (event.source) event.source.postMessage(data);
  };
  if (msg.type === 'SKIP_WAITING') {
    self.skipWaiting();
  } else if (msg.type === 'CACHE_URLS') {
    event.waitUntil(cacheUrls(msg.urls).then(() => reply({ type: 'vibora-sw-cached' })));
  } else if (msg.type === 'STATUS') {
    event.waitUntil(status().then((s) => reply({ type: 'vibora-sw-status', ...s })));
  }
});
